// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssm.proto

package org.lzbruby.ssm.domain.protobuf;

public final class Ssm {
  private Ssm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MapEntityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string key = 1;
    /**
     * <code>optional string key = 1;</code>
     */
    boolean hasKey();
    /**x
     * <code>optional string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // optional string value = 2;
    /**
     * <code>optional string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code org.lzbruby.ssm.domain.protobuf.MapEntity}
   */
  public static final class MapEntity extends
      com.google.protobuf.GeneratedMessage
      implements MapEntityOrBuilder {
    // Use MapEntity.newBuilder() to construct.
    private MapEntity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MapEntity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MapEntity defaultInstance;
    public static MapEntity getDefaultInstance() {
      return defaultInstance;
    }

    public MapEntity getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MapEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.class, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder.class);
    }

    public static com.google.protobuf.Parser<MapEntity> PARSER =
        new com.google.protobuf.AbstractParser<MapEntity>() {
      public MapEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapEntity(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MapEntity> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>optional string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>optional string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.lzbruby.ssm.domain.protobuf.MapEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.class, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder.class);
      }

      // Construct using org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_descriptor;
      }

      public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity getDefaultInstanceForType() {
        return org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.getDefaultInstance();
      }

      public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity build() {
        org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity buildPartial() {
        org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity result = new org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity) {
          return mergeFrom((org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity other) {
        if (other == org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // optional string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.lzbruby.ssm.domain.protobuf.MapEntity)
    }

    static {
      defaultInstance = new MapEntity(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.lzbruby.ssm.domain.protobuf.MapEntity)
  }

  public interface SessionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 sessionId = 1;
    /**
     * <code>optional int64 sessionId = 1;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional int64 sessionId = 1;</code>
     */
    long getSessionId();

    // repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    java.util.List<org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity> 
        getAttributesList();
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity getAttributes(int index);
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    int getAttributesCount();
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    java.util.List<? extends org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> 
        getAttributesOrBuilderList();
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder getAttributesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.lzbruby.ssm.domain.protobuf.Session}
   */
  public static final class Session extends
      com.google.protobuf.GeneratedMessage
      implements SessionOrBuilder {
    // Use Session.newBuilder() to construct.
    private Session(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Session(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Session defaultInstance;
    public static Session getDefaultInstance() {
      return defaultInstance;
    }

    public Session getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Session(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sessionId_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                attributes_ = new java.util.ArrayList<org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity>();
                mutable_bitField0_ |= 0x00000002;
              }
              attributes_.add(input.readMessage(org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_Session_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_Session_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.lzbruby.ssm.domain.protobuf.Ssm.Session.class, org.lzbruby.ssm.domain.protobuf.Ssm.Session.Builder.class);
    }

    public static com.google.protobuf.Parser<Session> PARSER =
        new com.google.protobuf.AbstractParser<Session>() {
      public Session parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Session(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Session> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 sessionId = 1;
    public static final int SESSIONID_FIELD_NUMBER = 1;
    private long sessionId_;
    /**
     * <code>optional int64 sessionId = 1;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 sessionId = 1;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    // repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;
    public static final int ATTRIBUTES_FIELD_NUMBER = 2;
    private java.util.List<org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity> attributes_;
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    public java.util.List<org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity> getAttributesList() {
      return attributes_;
    }
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    public java.util.List<? extends org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    public int getAttributesCount() {
      return attributes_.size();
    }
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity getAttributes(int index) {
      return attributes_.get(index);
    }
    /**
     * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
     */
    public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }

    private void initFields() {
      sessionId_ = 0L;
      attributes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sessionId_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(2, attributes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sessionId_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, attributes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.lzbruby.ssm.domain.protobuf.Ssm.Session parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.lzbruby.ssm.domain.protobuf.Ssm.Session prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.lzbruby.ssm.domain.protobuf.Session}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.lzbruby.ssm.domain.protobuf.Ssm.SessionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_Session_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_Session_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.lzbruby.ssm.domain.protobuf.Ssm.Session.class, org.lzbruby.ssm.domain.protobuf.Ssm.Session.Builder.class);
      }

      // Construct using org.lzbruby.ssm.domain.protobuf.Ssm.Session.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sessionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.lzbruby.ssm.domain.protobuf.Ssm.internal_static_org_lzbruby_ssm_domain_protobuf_Session_descriptor;
      }

      public org.lzbruby.ssm.domain.protobuf.Ssm.Session getDefaultInstanceForType() {
        return org.lzbruby.ssm.domain.protobuf.Ssm.Session.getDefaultInstance();
      }

      public org.lzbruby.ssm.domain.protobuf.Ssm.Session build() {
        org.lzbruby.ssm.domain.protobuf.Ssm.Session result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.lzbruby.ssm.domain.protobuf.Ssm.Session buildPartial() {
        org.lzbruby.ssm.domain.protobuf.Ssm.Session result = new org.lzbruby.ssm.domain.protobuf.Ssm.Session(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sessionId_ = sessionId_;
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.lzbruby.ssm.domain.protobuf.Ssm.Session) {
          return mergeFrom((org.lzbruby.ssm.domain.protobuf.Ssm.Session)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.lzbruby.ssm.domain.protobuf.Ssm.Session other) {
        if (other == org.lzbruby.ssm.domain.protobuf.Ssm.Session.getDefaultInstance()) return this;
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000002);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.lzbruby.ssm.domain.protobuf.Ssm.Session parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.lzbruby.ssm.domain.protobuf.Ssm.Session) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 sessionId = 1;
      private long sessionId_ ;
      /**
       * <code>optional int64 sessionId = 1;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 sessionId = 1;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>optional int64 sessionId = 1;</code>
       */
      public Builder setSessionId(long value) {
        bitField0_ |= 0x00000001;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sessionId = 1;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      // repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;
      private java.util.List<org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          attributes_ = new java.util.ArrayList<org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity>(attributes_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> attributesBuilder_;

      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public java.util.List<org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public Builder setAttributes(
          int index, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public Builder setAttributes(
          int index, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public Builder addAttributes(org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public Builder addAttributes(
          int index, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public Builder addAttributes(
          org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public Builder addAttributes(
          int index, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public Builder addAllAttributes(
          java.lang.Iterable<? extends org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          super.addAll(values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public java.util.List<? extends org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .org.lzbruby.ssm.domain.protobuf.MapEntity attributes = 2;</code>
       */
      public java.util.List<org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntity.Builder, org.lzbruby.ssm.domain.protobuf.Ssm.MapEntityOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.lzbruby.ssm.domain.protobuf.Session)
    }

    static {
      defaultInstance = new Session(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.lzbruby.ssm.domain.protobuf.Session)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_lzbruby_ssm_domain_protobuf_Session_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_lzbruby_ssm_domain_protobuf_Session_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tssm.proto\022\037org.lzbruby.ssm.domain.prot" +
      "obuf\"\'\n\tMapEntity\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t\"\\\n\007Session\022\021\n\tsessionId\030\001 \001(\003\022>\n\na" +
      "ttributes\030\002 \003(\0132*.org.lzbruby.ssm.domain" +
      ".protobuf.MapEntityB!\n\037org.lzbruby.ssm.d" +
      "omain.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_lzbruby_ssm_domain_protobuf_MapEntity_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_org_lzbruby_ssm_domain_protobuf_Session_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_lzbruby_ssm_domain_protobuf_Session_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_lzbruby_ssm_domain_protobuf_Session_descriptor,
              new java.lang.String[] { "SessionId", "Attributes", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
